- id: '1708472646046'
  alias: automation-motion-kitchen
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.sensor_kitchen_occupancy
    to: 'on'
    id: motion
  - platform: state
    entity_id:
    - binary_sensor.sensor_kitchen_occupancy
    to: 'off'
    id: no-motion
    for:
      hours: 0
      minutes: 2
      seconds: 30
  - platform: state
    entity_id:
    - light.light_kitchen_light
    to: 'on'
    for:
      hours: 0
      minutes: 10
      seconds: 0
    id: no-motion
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - motion
    - condition: state
      state: 'off'
      entity_id: light.light_kitchen_light
    then:
    - metadata: {}
      data: {}
      target:
        entity_id: light.light_kitchen_light
      action: light.turn_on
  - if:
    - condition: trigger
      id:
      - no-motion
    - condition: state
      state: 'on'
      entity_id: light.light_kitchen_light
    then:
    - metadata: {}
      data: {}
      target:
        entity_id: light.light_kitchen_light
      action: light.turn_off
  mode: single
- id: '1715010154294'
  alias: automation-evening
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.sensor_outside_illuminance
    for:
      hours: 0
      minutes: 0
      seconds: 0
    below: 2900
    id: turn-on-full
  - platform: numeric_state
    entity_id:
    - sensor.sensor_outside_illuminance
    for:
      hours: 0
      minutes: 20
      seconds: 0
    below: 10
    id: turn-on-evening
  - platform: numeric_state
    entity_id:
    - sensor.sensor_outside_illuminance
    for:
      hours: 0
      minutes: 10
      seconds: 0
    id: turn-off
    above: 3150
  - platform: time
    at: 01:00:00
    enabled: true
    id: turn-off
  condition:
  - condition: state
    entity_id: sensor.sun_solar_rising
    state: 'False'
    enabled: true
  action:
  - if:
    - condition: trigger
      id:
      - turn-on-full
      enabled: true
    - condition: state
      entity_id: binary_sensor.sensor_inside_motion
      state: 'on'
    then:
    - action: script.script_lights_bypass
      metadata: {}
      data:
        transition: 120
        script: script.script_lights_full
  - if:
    - condition: trigger
      id:
      - turn-on-evening
      enabled: true
    - condition: state
      entity_id: light.lights_all
      state: 'on'
    then:
    - action: script.script_lights_bypass
      metadata: {}
      data:
        transition: 900
        script: script.script_lights_evening
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: light.lights_all
      state: 'on'
    then:
    - metadata: {}
      data:
        transition: 30
      target:
        entity_id: light.lights_all
      action: light.turn_off
    enabled: true
  mode: single
- id: '1716369171251'
  alias: automation-morning
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
    id: turn-on-time
  - platform: time
    at: input_datetime.time_morning_lights_offset
    id: turn-on-alarm
    enabled: true
  - platform: numeric_state
    entity_id:
    - sensor.sensor_ceiling_illuminance
    id: turn-off
    above: 65
  condition:
  - condition: state
    entity_id: sensor.sun_solar_rising
    state: 'True'
    enabled: true
  action:
  - if:
    - condition: trigger
      id:
      - turn-on-time
      - turn-on-alarm
      enabled: true
    - condition: template
      value_template: '{{ (trigger.id in [''turn-on-alarm''] or trigger.id in [''turn-on-time'']
        and states(''sensor.pixel_8_next_alarm'') in ["unknown","unavailable"]) and
        is_state(''input_boolean.boolean_morning_lights_routine'', ''off'') }}'
      enabled: true
    then:
    - action: script.script_lights_bypass
      metadata: {}
      data:
        script: script.script_lights_full
        transition: 900
    - metadata: {}
      data: {}
      target:
        entity_id: input_boolean.boolean_morning_lights_routine
      action: input_boolean.turn_on
    enabled: true
  - if:
    - condition: trigger
      id:
      - turn-off
      enabled: true
    - condition: state
      entity_id: light.lights_all
      state: 'on'
    then:
    - metadata: {}
      data:
        transition: 30
      target:
        entity_id: light.lights_all
      action: light.turn_off
    enabled: true
  mode: single
- id: '1716546587327'
  alias: automation-door
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.sensor_door_opening
    to: 'on'
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - metadata: {}
    data:
      message: '{{ now().strftime(''%H:%M'') }} | FRONT DOOR IS STILL OPEN'
    action: notify.notify
  mode: single
- id: '1717852366829'
  alias: automation-air-purifier
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.i_9psl_pm2_5
    above: 5
    id: turn-on
  - platform: numeric_state
    entity_id:
    - sensor.i_9psl_pm10
    above: 15
    id: turn-on
  - platform: numeric_state
    entity_id:
    - sensor.i_9psl_pm2_5
    - sensor.i_9psl_pm10
    id: turn-off
    below: 3
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - turn-on
    - condition: state
      entity_id: switch.plug_air_purifier_switch
      state: 'off'
    then:
    - metadata: {}
      data: {}
      target:
        entity_id:
        - switch.plug_air_purifier_switch
      action: switch.turn_on
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: switch.plug_air_purifier_switch
      state: 'on'
    then:
    - metadata: {}
      data: {}
      target:
        entity_id:
        - switch.plug_air_purifier_switch
      action: switch.turn_off
  mode: single
- id: '1718114251248'
  alias: automation-receiver
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.philips_43pus8506_2
    to: 'on'
    id: turn-on
    from: 'off'
  - platform: state
    entity_id:
    - media_player.philips_43pus8506_2
    from: 'on'
    to: 'off'
    id: turn-off
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - turn-on
    - condition: state
      entity_id: media_player.denon_dra_800h
      state: 'off'
    then:
    - metadata: {}
      data: {}
      target:
        entity_id: media_player.denon_dra_800h
      action: media_player.turn_on
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: media_player.denon_dra_800h
      state: 'on'
    then:
    - metadata: {}
      data: {}
      target:
        entity_id: media_player.denon_dra_800h
      action: media_player.turn_off
  mode: single
- id: '1719353854773'
  alias: automation-away-from-home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.sensor_inside_motion
    to: 'off'
    for:
      hours: 0
      minutes: 20
      seconds: 0
    enabled: true
  condition: []
  action:
  - if:
    - condition: state
      entity_id: light.lights_all
      state: 'on'
    then:
    - metadata: {}
      data: {}
      target:
        entity_id: light.lights_all
      action: light.turn_off
  - action: notify.notify
    metadata: {}
    data:
      message: '{{ now().strftime(''%H:%M'') }} | AWAY'
  mode: single
- id: '1719353980068'
  alias: automation-coming-home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.sensor_door_opening
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.sensor_inside_motion
    state: 'off'
  - condition: state
    entity_id: light.lights_all
    state: 'off'
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.sensor_outside_illuminance
        below: 10
      sequence:
      - action: script.script_lights_evening
        metadata: {}
        data:
          transition: 1
    - conditions:
      - condition: numeric_state
        entity_id: sensor.sensor_outside_illuminance
        below: 2900
      sequence:
      - action: script.script_lights_full
        metadata: {}
        data:
          transition: 1
  mode: single
- id: '1722085260749'
  alias: automation-tv
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.philips_43pus8506_2
    attribute: app_id
    to: com.google.android.tvlauncher
    for:
      hours: 0
      minutes: 20
      seconds: 0
  condition: []
  action:
  - metadata: {}
    data: {}
    target:
      entity_id: remote.philips_43pus8506
    action: remote.turn_off
  mode: single
- id: '1723589298339'
  alias: automation-morning-boolean
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.sun_solar_rising
    to: 'False'
  condition: []
  action:
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.boolean_morning_lights_routine
  mode: single
- id: '1723589457542'
  alias: automation-morning-alarm
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.pixel_8_next_alarm
  condition: []
  action:
  - if:
    - condition: template
      value_template: '{{ trigger.to_state.state in ["unknown","unavailable"] }}'
    then:
    - metadata: {}
      data:
        datetime: '1970-01-01 00:00:00'
      target:
        entity_id: input_datetime.time_morning_lights_offset
      action: input_datetime.set_datetime
    else:
    - metadata: {}
      data:
        timestamp: '{{ (as_timestamp(trigger.to_state.state) | int ) - 15*60 }}'
      target:
        entity_id: input_datetime.time_morning_lights_offset
      action: input_datetime.set_datetime
  mode: single
