- id: '1708472646046'
  alias: automation-motion-kitchen
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.sensor_kitchenn_occupancy_4
    to: 'on'
    id: motion
  - platform: state
    entity_id:
    - binary_sensor.sensor_kitchenn_occupancy_4
    to: 'off'
    id: no-motion
    for:
      hours: 0
      minutes: 2
      seconds: 0
  - platform: state
    entity_id:
    - light.light_kitchen_light
    to: 'on'
    for:
      hours: 0
      minutes: 30
      seconds: 0
    id: no-motion
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - motion
    - condition: state
      state: 'off'
      entity_id: light.light_kitchen_light
    then:
    - service: light.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: light.light_kitchen_light
  - if:
    - condition: trigger
      id:
      - no-motion
    - condition: state
      state: 'on'
      entity_id: light.light_kitchen_light
    then:
    - service: light.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: light.light_kitchen_light
  mode: single
- id: '1715010154294'
  alias: automation-evening
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.sensor_outside_illuminance
    for:
      hours: 0
      minutes: 0
      seconds: 0
    below: 3000
    id: turn-on-full
  - platform: numeric_state
    entity_id:
    - sensor.sensor_outside_illuminance
    for:
      hours: 1
      minutes: 0
      seconds: 0
    below: 100
    id: turn-on-evening
  - platform: numeric_state
    entity_id:
    - sensor.sensor_outside_illuminance
    for:
      hours: 0
      minutes: 10
      seconds: 0
    id: turn-off
    above: 3250
  - platform: time
    at: 01:00:00
    enabled: true
    id: turn-off
  condition:
  - condition: state
    entity_id: sensor.sun_solar_rising
    state: 'False'
    enabled: true
  action:
  - if:
    - condition: trigger
      id:
      - turn-on-full
      enabled: true
    then:
    - if:
      - condition: state
        entity_id: light.light_all
        state: 'off'
      then:
      - service: light.turn_on
        metadata: {}
        data:
          brightness_pct: 2
        target:
          entity_id: light.light_startup
      enabled: true
    - service: script.script_lights_full
      metadata: {}
      data:
        transition: 120
  - if:
    - condition: trigger
      id:
      - turn-on-evening
      enabled: true
    - condition: state
      entity_id: light.light_all
      state: 'on'
    then:
    - service: script.script_lights_evening
      metadata: {}
      data:
        transition: 600
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: light.light_all
      state: 'on'
    then:
    - service: light.turn_off
      metadata: {}
      data:
        transition: 30
      target:
        entity_id: light.light_all
    enabled: true
  mode: single
- id: '1716369171251'
  alias: automation-morning
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
    id: turn-on-time
  - platform: time
    at: input_datetime.helper_time_offset
    id: turn-on-alarm
    enabled: true
  - platform: numeric_state
    entity_id:
    - sensor.sensor_inside_illuminance
    above: 150
    id: turn-off
  - platform: state
    entity_id:
    - sensor.sun_solar_rising
    to: 'False'
    id: turn-off-helper
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - turn-on-time
      - turn-on-alarm
      enabled: true
    - condition: state
      entity_id: sensor.sun_solar_rising
      state: 'True'
    - condition: template
      value_template: '{{ (trigger.id in [''turn-on-alarm''] or trigger.id in [''turn-on-time'']
        and states(''sensor.pixel_8_next_alarm'') in ["unknown","unavailable"]) and
        is_state(''input_boolean.helper_already_turned_on'', ''off'') }}'
      enabled: true
    then:
    - if:
      - condition: state
        entity_id: light.light_all
        state: 'off'
      then:
      - service: light.turn_on
        metadata: {}
        data:
          brightness_pct: 2
        target:
          entity_id: light.light_startup
      enabled: true
    - service: script.script_lights_full
      metadata: {}
      data:
        transition: 900
    - service: input_boolean.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: input_boolean.helper_already_turned_on
    enabled: true
  - if:
    - condition: trigger
      id:
      - turn-off
      enabled: true
    - condition: state
      entity_id: sensor.sun_solar_rising
      state: 'True'
    - condition: state
      entity_id: light.light_all
      state: 'on'
    then:
    - service: light.turn_off
      metadata: {}
      data:
        transition: 30
      target:
        entity_id: light.light_all
    enabled: true
  - if:
    - condition: trigger
      id:
      - turn-off-helper
      enabled: true
    then:
    - service: input_boolean.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: input_boolean.helper_already_turned_on
    enabled: true
  mode: single
- id: '1716546587327'
  alias: automation-door
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.sensor_door_opening
    to: 'on'
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    metadata: {}
    data:
      message: '{{ now().strftime(''%H:%M'') }} | FRONT DOOR IS STILL OPEN'
  mode: single
- id: '1717852366829'
  alias: automation-air-purifier
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.i_9psl_pm2_5
    above: 5
    id: turn-on
  - platform: numeric_state
    entity_id:
    - sensor.i_9psl_pm10
    above: 15
    id: turn-on
  - platform: numeric_state
    entity_id:
    - sensor.i_9psl_pm2_5
    - sensor.i_9psl_pm10
    id: turn-off
    below: 3
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - turn-on
    - condition: state
      entity_id: switch.plug_air_purifier_switch
      state: 'off'
    then:
    - service: switch.turn_on
      metadata: {}
      data: {}
      target:
        entity_id:
        - switch.plug_air_purifier_switch
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: switch.plug_air_purifier_switch
      state: 'on'
    then:
    - service: switch.turn_off
      metadata: {}
      data: {}
      target:
        entity_id:
        - switch.plug_air_purifier_switch
  mode: single
- id: '1718114251248'
  alias: automation-receiver
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.philips_43pus8506_2
    from: 'off'
    to: 'on'
    id: turn-on
  - platform: state
    entity_id:
    - media_player.philips_43pus8506_2
    from: 'on'
    to: 'off'
    id: turn-off
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - turn-on
    - condition: state
      entity_id: media_player.denon_dra_800h
      state: 'off'
    then:
    - service: media_player.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: media_player.denon_dra_800h
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: media_player.denon_dra_800h
      state: 'on'
    then:
    - service: media_player.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: media_player.denon_dra_800h
  mode: single
- id: '1718215321142'
  alias: automation-smartphone-alarm
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.pixel_8_next_alarm
  condition: []
  action:
  - if:
    - condition: template
      value_template: '{{ trigger.to_state.state in ["unknown","unavailable"] }}'
    then:
    - service: input_datetime.set_datetime
      metadata: {}
      data:
        datetime: '1970-01-01 00:00:00'
      target:
        entity_id: input_datetime.helper_time_offset
    else:
    - service: input_datetime.set_datetime
      metadata: {}
      data:
        timestamp: '{{ (as_timestamp(trigger.to_state.state) | int ) - 15*60 }}'
      target:
        entity_id: input_datetime.helper_time_offset
  mode: single
- id: '1719353854773'
  alias: automation-away-from-home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.sensor_inside_motion
    to: 'off'
    for:
      hours: 0
      minutes: 30
      seconds: 0
    enabled: true
  condition:
  - condition: state
    entity_id: light.light_all
    state: 'on'
  action:
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.light_all
  mode: single
- id: '1719353980068'
  alias: automation-coming-home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.sensor_door_opening
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.sensor_inside_motion
    state: 'off'
  - condition: state
    entity_id: light.light_all
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.sensor_outside_illuminance
    below: 3000
  action:
  - service: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.light_all
  mode: single
- id: '1720918538232'
  alias: automation-motion-working
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.sensor_working_area_occupancy
    to: 'on'
  condition:
  - condition: time
    before: 09:00:00
  - condition: state
    entity_id: light.light_all
    state: 'off'
    enabled: true
  action:
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 40
    target:
      entity_id: light.light_living_area_1_light
  - wait_for_trigger:
    - platform: state
      entity_id:
      - binary_sensor.sensor_working_area_occupancy
      to: 'off'
      for:
        hours: 0
        minutes: 1
        seconds: 0
    - platform: state
      entity_id:
      - light.light_all
      to: 'off'
    enabled: true
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.light_living_area_1_light
  mode: single
- id: '1722085260749'
  alias: automation-tv
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.philips_43pus8506_2
    attribute: app_id
    to: com.google.android.tvlauncher
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition:
  - condition: state
    state: 'on'
    enabled: true
    entity_id: media_player.philips_43pus8506_2
  action:
  - service: remote.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: remote.philips_43pus8506
  mode: single
