- id: '1717852366829'
  alias: automation-air-purifier
  description: ''
  triggers:
  - entity_id:
    - sensor.i_9psl_pm2_5
    above: 5
    id: turn-on
    trigger: numeric_state
  - entity_id:
    - sensor.i_9psl_pm10
    above: 15
    id: turn-on
    trigger: numeric_state
  - entity_id:
    - sensor.i_9psl_pm2_5
    - sensor.i_9psl_pm10
    id: turn-off
    below: 4
    for:
      hours: 0
      minutes: 5
      seconds: 0
    trigger: numeric_state
  conditions: []
  actions:
  - if:
    - condition: trigger
      id:
      - turn-on
    - condition: state
      entity_id: switch.plug_air_purifier_switch
      state: 'off'
    then:
    - metadata: {}
      data: {}
      target:
        entity_id:
        - switch.plug_air_purifier_switch
      action: switch.turn_on
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: switch.plug_air_purifier_switch
      state: 'on'
    then:
    - metadata: {}
      data: {}
      target:
        entity_id:
        - switch.plug_air_purifier_switch
      action: switch.turn_off
  mode: single
- id: '1722085260749'
  alias: automation-tv
  description: ''
  triggers:
  - entity_id:
    - media_player.philips_43pus8506_2
    attribute: app_id
    to: com.google.android.tvlauncher
    for:
      hours: 0
      minutes: 15
      seconds: 0
    trigger: state
  conditions: []
  actions:
  - metadata: {}
    data: {}
    target:
      entity_id: remote.philips_43pus8506
    action: remote.turn_off
  mode: single
- id: '1733714968098'
  alias: automation-phone
  description: ''
  triggers:
  - trigger: time
    at: 00:00:00
    id: low
  - trigger: time
    at: input_datetime.datetime_wakeup_time
    id: high
  conditions: []
  actions:
  - if:
    - condition: trigger
      id:
      - low
    then:
    - action: notify.notify
      metadata: {}
      data:
        message: command_screen_brightness_level
        data:
          command: 8
  - if:
    - condition: trigger
      id:
      - high
    then:
    - action: notify.notify
      metadata: {}
      data:
        message: command_screen_brightness_level
        data:
          command: 30
  mode: single
- id: '1741003586439'
  alias: automation-lights-illum
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.sensor_outside_balcony_illuminance
    below: input_number.number_illumination
    id: turn-on
  - trigger: numeric_state
    entity_id:
    - sensor.sensor_outside_balcony_illuminance
    for:
      hours: 0
      minutes: 1
      seconds: 30
    above: input_number.number_illumination
    id: turn-off
  conditions:
  - condition: state
    entity_id: sensor.sun_solar_rising
    state: 'False'
  actions:
  - if:
    - condition: trigger
      id:
      - turn-on
    - condition: state
      entity_id: light.lights_livingroom
      state: 'off'
    - condition: state
      entity_id: binary_sensor.sensor_livingroom_motion
      state: 'on'
    then:
    - action: script.turn_on
      metadata: {}
      data:
        variables:
          transition: 120
      target:
        entity_id: script.script_livingroom_lights_full
  - if:
    - condition: trigger
      id:
      - turn-on
    - condition: state
      entity_id: light.lights_bedroom
      state: 'off'
    - condition: state
      entity_id: binary_sensor.sensor_bedroom_motion
      state: 'on'
    then:
    - action: script.turn_on
      metadata: {}
      data:
        variables:
          transition: 120
      target:
        entity_id: script.script_bedroom_lights_full
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: light.lights_livingroom
      state: 'on'
    then:
    - action: light.turn_off
      metadata: {}
      data:
        transition: 30
      target:
        entity_id:
        - light.lights_livingroom
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: light.lights_bedroom
      state: 'on'
    then:
    - action: light.turn_off
      metadata: {}
      data:
        transition: 30
      target:
        entity_id: light.lights_bedroom
  mode: single
- id: '1741004005554'
  alias: automation-lights-time
  description: ''
  triggers:
  - trigger: template
    value_template: '{% set hours = as_timestamp(states(''sensor.sun_next_dusk''))
      | timestamp_custom(''%H'') | int %}

      {% set min = as_timestamp(states(''sensor.sun_next_dusk'')) | timestamp_custom(''%M'')
      | int %}

      {% set ratio = 6/10 %}

      {{ as_timestamp(now()) | timestamp_custom(''%H:%M'') == (((24-hours-min/60)*ratio+hours+min/60)*60*60)
      | timestamp_custom(''%H:%M'', false) }}'
  conditions: []
  actions:
  - if:
    - condition: state
      entity_id: light.lights_livingroom
      attribute: color_mode
      state: color_temp
    then:
    - action: script.turn_on
      metadata: {}
      data:
        variables:
          transition: 600
      target:
        entity_id: script.script_livingroom_lights_color
  - if:
    - condition: state
      entity_id: light.lights_bedroom
      attribute: color_mode
      state: color_temp
    then:
    - action: script.turn_on
      metadata: {}
      data:
        variables:
          transition: 600
      target:
        entity_id: script.script_bedroom_lights_color
  mode: single
- id: '1741029409508'
  alias: automation-lights-motion-bedroom
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.sensor_bedroom_entry_occupancy
    to: 'on'
    id: turn-on
    from: 'off'
  - trigger: state
    entity_id:
    - binary_sensor.sensor_bedroom_motion
    to: 'off'
    for:
      hours: 0
      minutes: 2
      seconds: 30
    id: turn-off
    from: 'on'
  conditions: []
  actions:
  - if:
    - condition: trigger
      id:
      - turn-on
    - condition: state
      entity_id: light.lights_bedroom
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.sensor_outside_balcony_illuminance
      below: input_number.number_illumination
    then:
    - choose:
      - conditions:
        - condition: time
          before: input_datetime.datetime_wakeup_time
        sequence: []
      - conditions:
        - condition: template
          value_template: '{% set hours = as_timestamp(states(''sensor.sun_next_dusk''))
            | timestamp_custom(''%H'') | int %}

            {% set min = as_timestamp(states(''sensor.sun_next_dusk'')) | timestamp_custom(''%M'')
            | int %}

            {% set ratio = 6/10 %}

            {{ as_timestamp(now()) | timestamp_custom(''%H:%M'') > (((24-hours-min/60)*ratio+hours+min/60)*60*60)
            | timestamp_custom(''%H:%M'', false) }}'
        sequence:
        - action: script.turn_on
          metadata: {}
          data:
            variables:
              transition: 1
          target:
            entity_id:
            - script.script_bedroom_lights_color
      default:
      - action: script.turn_on
        metadata: {}
        data:
          variables:
            transition: 1
        target:
          entity_id: script.script_bedroom_lights_full
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: light.lights_bedroom
      state: 'on'
    then:
    - action: light.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: light.lights_bedroom
  mode: single
- id: '1741029438832'
  alias: automation-lights-motion-livingroom
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.sensor_livingroom_motion
    to: 'on'
    id: turn-on
    from: 'off'
  - trigger: state
    entity_id:
    - binary_sensor.sensor_livingroom_motion
    to: 'off'
    for:
      hours: 0
      minutes: 2
      seconds: 30
    id: turn-off
    from: 'on'
  conditions: []
  actions:
  - if:
    - condition: trigger
      id:
      - turn-on
    - condition: state
      entity_id: light.lights_livingroom
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.sensor_outside_balcony_illuminance
      below: input_number.number_illumination
    then:
    - choose:
      - conditions:
        - condition: time
          before: input_datetime.datetime_wakeup_time
        sequence:
        - action: script.turn_on
          metadata: {}
          data:
            variables:
              transition: 1
          target:
            entity_id:
            - script.script_livingroom_lights_color_soft
      - conditions:
        - condition: template
          value_template: '{% set hours = as_timestamp(states(''sensor.sun_next_dusk''))
            | timestamp_custom(''%H'') | int %}

            {% set min = as_timestamp(states(''sensor.sun_next_dusk'')) | timestamp_custom(''%M'')
            | int %}

            {% set ratio = 6/10 %}

            {{ as_timestamp(now()) | timestamp_custom(''%H:%M'') > (((24-hours-min/60)*ratio+hours+min/60)*60*60)
            | timestamp_custom(''%H:%M'', false) }}'
        sequence:
        - action: script.turn_on
          metadata: {}
          data:
            variables:
              transition: 1
          target:
            entity_id:
            - script.script_livingroom_lights_color
      default:
      - action: script.turn_on
        metadata: {}
        data:
          variables:
            transition: 1
        target:
          entity_id: script.script_livingroom_lights_full
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: light.lights_livingroom
      state: 'on'
    then:
    - action: light.turn_off
      metadata: {}
      data: {}
      target:
        entity_id:
        - light.lights_livingroom
  mode: single
- id: '1741088261703'
  alias: automation-lights-morning
  description: ''
  triggers:
  - at: input_datetime.datetime_wakeup_time
    id: turn-on
    trigger: time
  - entity_id:
    - sensor.sensor_bedroom_entry_illuminance
    id: turn-off
    above: 60
    trigger: numeric_state
    enabled: false
  conditions:
  - condition: state
    entity_id: sensor.sun_solar_rising
    state: 'True'
  actions:
  - if:
    - condition: trigger
      id:
      - turn-on
    - condition: state
      entity_id: binary_sensor.sensor_bedroom_motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.boolean_wakeup_lights
      state: 'off'
    then:
    - metadata: {}
      data: {}
      target:
        entity_id:
        - input_boolean.boolean_wakeup_lights
      action: input_boolean.turn_on
    - action: script.turn_on
      metadata: {}
      data:
        variables:
          transition: 1200
      target:
        entity_id: script.script_bedroom_lights_full
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: light.lights_bedroom
      state: 'on'
    then:
    - metadata: {}
      data:
        transition: 30
      target:
        entity_id:
        - light.lights_bedroom
      action: light.turn_off
  mode: single
- id: '1741088287959'
  alias: automation-lights-remote
  description: ''
  triggers:
  - device_id: 7e0df21fba2ff631d282063e7bc97f81
    domain: zha
    type: remote_button_short_press
    subtype: turn_on
    trigger: device
    id: turn-on-bed
  - device_id: 7e0df21fba2ff631d282063e7bc97f81
    domain: zha
    type: remote_button_short_press
    subtype: turn_off
    trigger: device
    id: turn-off-bed
  - device_id: 7e0df21fba2ff631d282063e7bc97f81
    domain: zha
    type: remote_button_short_press
    subtype: right
    trigger: device
    id: turn-on-living
  - device_id: 7e0df21fba2ff631d282063e7bc97f81
    domain: zha
    type: remote_button_short_press
    subtype: left
    trigger: device
    id: turn-off-living
  conditions: []
  actions:
  - if:
    - condition: trigger
      id:
      - turn-on-bed
    - condition: state
      entity_id: light.lights_bedroom
      state: 'off'
    then:
    - action: script.turn_on
      metadata: {}
      data:
        variables:
          transition: 1
      target:
        entity_id: script.script_bedroom_lights_color
  - if:
    - condition: trigger
      id:
      - turn-off-bed
    - condition: state
      entity_id: light.lights_bedroom
      state: 'on'
    then:
    - action: light.turn_off
      metadata: {}
      data: {}
      target:
        entity_id:
        - light.lights_bedroom
  - if:
    - condition: trigger
      id:
      - turn-on-living
    - condition: state
      entity_id: light.lights_livingroom
      state: 'off'
    then:
    - action: script.turn_on
      metadata: {}
      data:
        variables:
          transition: 1
      target:
        entity_id:
        - script.script_livingroom_lights_color
  - if:
    - condition: trigger
      id:
      - turn-off-living
    - condition: state
      entity_id: light.lights_livingroom
      state: 'on'
    then:
    - action: light.turn_off
      metadata: {}
      data: {}
      target:
        entity_id:
        - light.lights_livingroom
  mode: single
- id: '1741088398150'
  alias: automation-lights-morning-wakeup-time
  description: ''
  triggers:
  - entity_id:
    - sensor.pixel_8_next_alarm
    trigger: state
  - trigger: time
    at: 00:00:00
  conditions:
  - condition: state
    entity_id: input_boolean.boolean_wakeup_lights
    state: 'off'
  actions:
  - if:
    - condition: template
      value_template: '{{ states(''sensor.pixel_8_next_alarm'') in ["unknown","unavailable"]
        }}'
    then:
    - metadata: {}
      data:
        timestamp: '{{ as_timestamp(today_at(''09:30'')) | int }}'
      target:
        entity_id: input_datetime.datetime_wakeup_time
      action: input_datetime.set_datetime
    else:
    - metadata: {}
      data:
        timestamp: '{{ (as_timestamp(trigger.to_state.state) | int ) - 10*60 }}'
      target:
        entity_id: input_datetime.datetime_wakeup_time
      action: input_datetime.set_datetime
      enabled: false
    - metadata: {}
      data:
        timestamp: '{{ as_timestamp(states(''sensor.pixel_8_next_alarm'')) | int -
          10*60 }}'
      target:
        entity_id: input_datetime.datetime_wakeup_time
      action: input_datetime.set_datetime
  mode: single
- id: '1741088451864'
  alias: automation-lights-morning-wakeup-boolean
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.sun_solar_rising
    to: 'False'
  conditions:
  - condition: state
    entity_id: input_boolean.boolean_wakeup_lights
    state: 'on'
  actions:
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
      - input_boolean.boolean_wakeup_lights
  mode: single
