- id: '1706919178130'
  alias: automation-evening
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.sun_solar_elevation
    below: 13
    id: turn-lights-on
    enabled: true
  - platform: time
    at: 01:00:00
    enabled: true
    id: turn-lights-off
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - turn-lights-on
    - condition: state
      entity_id: light.helper_evening_entities
      state: 'off'
    then:
    - service: light.turn_on
      target:
        entity_id:
        - light.helper_evening
      data:
        kelvin: 2700
        brightness_pct: 1
    - service: light.turn_on
      target:
        entity_id:
        - light.helper_evening_full
      data:
        transition: 600
        brightness_pct: 100
    - service: light.turn_on
      data:
        transition: 600
        brightness_pct: 60
      target:
        entity_id:
        - light.helper_evening_dim
    - service: notify.notify
      metadata: {}
      data:
        message: EVENING - ON
  - if:
    - condition: trigger
      id:
      - turn-lights-off
    - condition: state
      entity_id: light.helper_all
      state: 'on'
    then:
    - service: light.turn_off
      target:
        entity_id:
        - light.helper_all
      data: {}
    - service: notify.notify
      metadata: {}
      data:
        message: EVENING - OFF
    enabled: true
  mode: single
- id: '1707333453641'
  alias: automation-morning
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.kb2003_next_alarm
    id: set-time
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - platform: time
    at: input_datetime.helper_time_offset
    id: action-on-alarm
    enabled: true
  - platform: numeric_state
    entity_id:
    - sensor.sun_solar_elevation
    above: 9
    id: action-on-sun
    enabled: true
  - platform: time
    at: '12:00:00'
    id: action-off
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - set-time
    then:
    - if:
      - condition: template
        value_template: '{{ trigger.to_state.state in ["unknown","unavailable"] }}'
      then:
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.helper_time_offset
        data:
          datetime: '1970-01-01 00:00:00'
      else:
      - variables:
          offset_alarm: 15
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.helper_time_offset
        data:
          timestamp: '{{ (as_timestamp(trigger.to_state.state) | int ) - offset_alarm*60
            }}'
        enabled: true
      enabled: true
    enabled: true
  - if:
    - condition: trigger
      id:
      - action-on-alarm
      - action-on-sun
    - condition: template
      value_template: '{% set x = now().hour < 12 %}

        {{ x if trigger.id in [''action-on-alarm''] else True }}

        '
      enabled: true
    - condition: template
      value_template: '{% set x = states(''sensor.kb2003_next_alarm'') in ["unknown","unavailable"]
        %}

        {% set y = now().hour >= 12 %}

        {{ x or y if trigger.id in [''action-on-sun''] else True }}

        '
      enabled: true
    - condition: state
      entity_id: light.helper_morning_entities
      state: 'off'
    then:
    - service: light.turn_on
      target:
        entity_id:
        - light.helper_morning
      data:
        brightness_pct: 1
        kelvin: 4000
    - service: light.turn_on
      target:
        entity_id:
        - light.helper_morning
      data:
        brightness_pct: 100
        transition: 600
    - service: notify.notify
      metadata: {}
      data:
        message: MORNING - ON
    - delay:
        hours: 0
        minutes: 15
        seconds: 0
        milliseconds: 0
    - service: light.turn_on
      target:
        entity_id: light.helper_morning
      data:
        kelvin: 2700
        transition: 600
    enabled: true
  - if:
    - condition: trigger
      id:
      - action-off
      enabled: true
    - condition: state
      entity_id: light.helper_morning
      state: 'on'
    then:
    - service: light.turn_off
      target:
        entity_id:
        - light.helper_morning
      data: {}
    - service: notify.notify
      metadata: {}
      data:
        message: MORNING - OFF
    enabled: true
  mode: single
- id: '1707575532928'
  alias: automation-remote-all
  description: ''
  trigger:
  - device_id: 279e9dd0d4863fd5f70847462c76ff2c
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
    id: turn-on
  - device_id: 279e9dd0d4863fd5f70847462c76ff2c
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
    id: turn-off
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - turn-on
    - condition: state
      entity_id: light.helper_all_entities
      state: 'off'
    then:
    - service: light.turn_on
      data: {}
      target:
        entity_id: light.helper_all
    - service: notify.notify
      metadata: {}
      data:
        message: REMOTE - ON
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: light.helper_all
      state: 'on'
    then:
    - service: light.turn_off
      data: {}
      target:
        entity_id:
        - light.helper_all
    - service: notify.notify
      metadata: {}
      data:
        message: REMOTE - OFF
  mode: single
- id: '1708472646046'
  alias: automation-motion-kitchen
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.motion_sensor_kitchen_occupancy
    to: 'on'
    id: motion
  - platform: state
    entity_id:
    - binary_sensor.motion_sensor_kitchen_occupancy
    to: 'off'
    id: no-motion
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - motion
    - condition: state
      entity_id: light.helper_motion_kitchen
      state: 'off'
    then:
    - service: light.turn_on
      target:
        entity_id:
        - light.helper_motion_kitchen
      data:
        kelvin: 2700
        brightness_pct: 90
    - service: notify.notify
      metadata: {}
      data:
        message: MOTION KITCHEN - ON
  - if:
    - condition: trigger
      id:
      - no-motion
    - condition: state
      entity_id: light.helper_motion_kitchen
      state: 'on'
    then:
    - service: light.turn_off
      target:
        entity_id:
        - light.helper_motion_kitchen
      data: {}
    - service: notify.notify
      metadata: {}
      data:
        message: MOTION KITCHEN - OFF
  mode: single
- id: '1708554610064'
  alias: automation-motion-bed
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.motion_sensor_bed_occupancy
    id: motion
    for:
      hours: 0
      minutes: 0
      seconds: 0
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.motion_sensor_bed_occupancy
    to: 'off'
    id: no-motion
    for:
      hours: 0
      minutes: 0
      seconds: 30
  condition:
  - condition: time
    after: 00:00:00
    before: '12:00:00'
  action:
  - if:
    - condition: trigger
      id:
      - motion
    - condition: state
      entity_id: light.helper_all
      state: 'off'
    then:
    - service: light.turn_on
      target:
        entity_id:
        - light.helper_motion_bed
      data:
        kelvin: 2700
        brightness_pct: 70
    - service: notify.notify
      metadata: {}
      data:
        message: MOTION BED - ON
  - if:
    - condition: trigger
      id:
      - no-motion
    - condition: state
      entity_id: light.helper_motion_bed
      state: 'on'
    then:
    - service: light.turn_off
      target:
        entity_id:
        - light.helper_motion_bed
      data: {}
    - service: notify.notify
      metadata: {}
      data:
        message: MOTION BED - OFF
  mode: single
