- id: '1708472646046'
  alias: automation-motion-kitchen
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.signify_netherlands_b_v_sml003_occupancy_4
    to: 'on'
    id: motion
  - platform: state
    entity_id:
    - binary_sensor.signify_netherlands_b_v_sml003_occupancy_4
    to: 'off'
    id: no-motion
    for:
      hours: 0
      minutes: 2
      seconds: 0
  - platform: state
    entity_id:
    - light.helper_light_kitchen
    to: 'on'
    for:
      hours: 0
      minutes: 30
      seconds: 0
    id: no-motion
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - motion
    - condition: state
      state: 'off'
      entity_id: light.helper_light_kitchen
    then:
    - service: light.turn_on
      target:
        entity_id:
        - light.helper_light_kitchen
      data: {}
  - if:
    - condition: trigger
      id:
      - no-motion
    - condition: state
      state: 'on'
      entity_id: light.helper_light_kitchen
    then:
    - service: light.turn_off
      target:
        entity_id:
        - light.helper_light_kitchen
      data: {}
  mode: single
- id: '1715010154294'
  alias: automation-evening
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.signify_netherlands_b_v_sml004_illuminance
    for:
      hours: 0
      minutes: 0
      seconds: 0
    below: 575
    id: turn-on
  - platform: numeric_state
    entity_id:
    - sensor.signify_netherlands_b_v_sml004_illuminance
    for:
      hours: 0
      minutes: 10
      seconds: 0
    id: turn-off
    above: 600
  - platform: time
    at: 01:00:00
    enabled: true
    id: turn-off
  condition:
  - condition: state
    entity_id: sensor.sun_solar_rising
    state: 'False'
  action:
  - if:
    - condition: trigger
      id:
      - turn-on
      enabled: true
    then:
    - if:
      - condition: state
        entity_id: light.helper_light_all
        state: 'off'
      then:
      - service: light.turn_on
        target:
          entity_id: light.helper_light_all
        data:
          brightness_pct: 1
    - service: adaptive_lighting.change_switch_settings
      data:
        entity_id: switch.adaptive_lighting_light_1
        autoreset_control_seconds: '120'
      enabled: true
    - service: adaptive_lighting.set_manual_control
      data:
        manual_control: true
        entity_id: switch.adaptive_lighting_light_1
      enabled: true
    - parallel:
      - service: light.turn_on
        data:
          brightness_pct: 100
          transition: 120
        enabled: true
        target:
          entity_id:
          - light.helper_light_bookcase
          - light.helper_light_bureau
          - light.silicon_labs_ezsp_zha_light_dining_table
      - service: light.turn_on
        target:
          entity_id:
          - light.helper_light_hall
        data:
          transition: 120
          brightness_pct: 25
        enabled: true
    - service: adaptive_lighting.change_switch_settings
      data:
        use_defaults: configuration
        entity_id: switch.adaptive_lighting_light_1
      enabled: true
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: light.helper_light_all
      state: 'on'
    then:
    - service: light.turn_off
      data:
        transition: 30
      target:
        entity_id: light.helper_light_all
    enabled: true
  mode: single
- id: '1716369171251'
  alias: automation-morning
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
    id: turn-on-time
  - platform: time
    at: input_datetime.helper_time_offset
    id: turn-on-alarm
    enabled: true
  - platform: numeric_state
    entity_id:
    - sensor.signify_netherlands_b_v_sml003_illuminance_3
    id: turn-off
    above: 40
  - platform: state
    entity_id:
    - sensor.sun_solar_rising
    id: turn-off-helper
  condition:
  - condition: state
    entity_id: sensor.sun_solar_rising
    state: 'True'
  action:
  - if:
    - condition: trigger
      id:
      - turn-on-time
      - turn-on-alarm
      enabled: true
    - condition: template
      value_template: "{% if now().hour < 12 %}\n  {{ (trigger.id in ['turn-on-alarm']
        or trigger.id in ['turn-on-time'] and states('sensor.kb2003_next_alarm') in
        [\"unknown\",\"unavailable\"]) and is_state('input_boolean.helper_already_turned_on',
        'off') }}\n{% else %}\n  {{ trigger.id in ['turn-on-time'] }}\n{% endif %}"
      enabled: true
    then:
    - if:
      - condition: state
        entity_id: light.helper_light_all
        state: 'off'
      then:
      - service: light.turn_on
        target:
          entity_id: light.helper_light_all
        data:
          brightness_pct: 1
    - service: adaptive_lighting.change_switch_settings
      data:
        entity_id: switch.adaptive_lighting_light_1
        autoreset_control_seconds: '900'
      enabled: true
    - service: adaptive_lighting.set_manual_control
      data:
        manual_control: true
        entity_id: switch.adaptive_lighting_light_1
      enabled: true
    - parallel:
      - service: light.turn_on
        target:
          entity_id:
          - light.helper_light_bureau
          - light.helper_light_bookcase
          - light.silicon_labs_ezsp_zha_light_dining_table
        data:
          brightness_pct: 100
          transition: 900
        enabled: true
      - service: light.turn_on
        target:
          entity_id:
          - light.helper_light_hall
        data:
          transition: 900
          brightness_pct: 25
        enabled: true
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.helper_already_turned_on
        data: {}
    - service: adaptive_lighting.change_switch_settings
      data:
        entity_id: switch.adaptive_lighting_light_1
        use_defaults: configuration
      enabled: true
    enabled: true
  - if:
    - condition: trigger
      id:
      - turn-off
      enabled: true
    - condition: state
      entity_id: light.helper_light_all
      state: 'on'
    then:
    - service: light.turn_off
      data:
        transition: 30
      target:
        entity_id:
        - light.helper_light_all
    enabled: true
  - if:
    - condition: trigger
      id:
      - turn-off-helper
      enabled: true
    then:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.helper_already_turned_on
      data: {}
    enabled: true
  mode: single
- id: '1716546587327'
  alias: automation-door
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.lumi_lumi_magnet_agl02_opening
    to: 'on'
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    metadata: {}
    data:
      message: '{{ now().strftime(''%H:%M'') }} | FRONT DOOR IS STILL OPEN'
  mode: single
- id: '1717852366829'
  alias: automation-air-purifier
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.i_9psl_pm2_5
    above: 5
    id: turn-on
  - platform: numeric_state
    entity_id:
    - sensor.i_9psl_pm10
    above: 15
    id: turn-on
  - platform: numeric_state
    entity_id:
    - sensor.i_9psl_pm2_5
    - sensor.i_9psl_pm10
    id: turn-off
    below: 2
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - turn-on
    - condition: state
      entity_id: switch.ikea_of_sweden_tretakt_smart_plug_switch
      state: 'off'
    then:
    - service: switch.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: switch.ikea_of_sweden_tretakt_smart_plug_switch
    - service: notify.notify
      metadata: {}
      data:
        message: '{{ now().strftime(''%H:%M'') }} | Air purifier ON'
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: switch.ikea_of_sweden_tretakt_smart_plug_switch
      state: 'on'
    then:
    - service: switch.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: switch.ikea_of_sweden_tretakt_smart_plug_switch
    - service: notify.notify
      metadata: {}
      data:
        message: '{{ now().strftime(''%H:%M'') }} | Air purifier OFF'
  mode: single
- id: '1718114251248'
  alias: automation-receiver
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.philips_43pus8506_2
    from: 'off'
    to: 'on'
    id: turn-on-tv
  - platform: state
    entity_id:
    - media_player.philips_43pus8506_2
    from: 'on'
    to: 'off'
    id: turn-off-tv
  - platform: state
    entity_id:
    - media_player.optoma_hd146x
    from: unavailable
    id: turn-on-beamer
    enabled: false
  - platform: state
    entity_id:
    - media_player.optoma_hd146x
    to: unavailable
    id: turn-off-beamer
    enabled: false
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - turn-on-beamer
      - turn-on-tv
    then:
    - if:
      - condition: state
        entity_id: media_player.denon_dra_800h
        state: 'off'
      then:
      - service: media_player.turn_on
        target:
          entity_id: media_player.denon_dra_800h
        data: {}
    - if:
      - condition: trigger
        id:
        - turn-on-beamer
      - condition: not
        conditions:
        - condition: state
          entity_id: media_player.denon_dra_800h
          attribute: source
          state: CBL/SAT
      then:
      - service: media_player.select_source
        target:
          entity_id: media_player.denon_dra_800h
        data:
          source: CBL/SAT
    - if:
      - condition: trigger
        id:
        - turn-on-tv
      - condition: not
        conditions:
        - condition: state
          entity_id: media_player.denon_dra_800h
          attribute: source
          state: TV Audio
      then:
      - service: media_player.select_source
        target:
          entity_id: media_player.denon_dra_800h
        data:
          source: TV Audio
  - if:
    - condition: trigger
      id:
      - turn-off-tv
      - turn-off-beamer
    - condition: state
      entity_id: media_player.denon_dra_800h
      state: 'on'
    then:
    - if:
      - condition: trigger
        id:
        - turn-off-tv
      - condition: state
        entity_id: media_player.denon_dra_800h
        attribute: source
        state: TV Audio
      then:
      - service: media_player.turn_off
        target:
          entity_id:
          - media_player.denon_dra_800h
        data: {}
    - if:
      - condition: trigger
        id:
        - turn-off-beamer
      - condition: state
        entity_id: media_player.denon_dra_800h
        attribute: source
        state: CBL/SAT
      then:
      - service: media_player.turn_off
        target:
          entity_id:
          - media_player.denon_dra_800h
        data: {}
  mode: single
- id: '1718215321142'
  alias: automation-smartphone-alarm
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.kb2003_next_alarm
  condition: []
  action:
  - if:
    - condition: template
      value_template: '{{ trigger.to_state.state in ["unknown","unavailable"] }}'
    then:
    - service: input_datetime.set_datetime
      target:
        entity_id: input_datetime.helper_time_offset
      data:
        datetime: '1970-01-01 00:00:00'
    else:
    - service: input_datetime.set_datetime
      target:
        entity_id: input_datetime.helper_time_offset
      data:
        timestamp: '{{ (as_timestamp(trigger.to_state.state) | int ) - 15*60 }}'
      enabled: true
  mode: single
- id: '1719353854773'
  alias: automation-away-from-home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.helper_motion_home
    to: 'off'
    for:
      hours: 1
      minutes: 0
      seconds: 0
  condition: []
  action:
  - if:
    - condition: state
      entity_id: light.helper_light_all
      state: 'on'
    then:
    - service: light.turn_off
      target:
        entity_id: light.helper_light_all
      data: {}
    - service: notify.notify
      metadata: {}
      data:
        message: '{{ now().strftime(''%H:%M'') }} | AWAY - turn OFF'
  mode: single
- id: '1719353980068'
  alias: automation-coming-home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.lumi_lumi_magnet_agl02_opening
    to: 'on'
  condition: []
  action:
  - if:
    - condition: state
      entity_id: binary_sensor.helper_motion_home
      state: 'off'
    - condition: state
      entity_id: light.helper_light_all
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.signify_netherlands_b_v_sml004_illuminance
      below: 575
    then:
    - service: light.turn_on
      target:
        entity_id: light.helper_light_all
      data: {}
  mode: single
