- id: '1717852366829'
  alias: automation-air-purifier
  description: ''
  triggers:
  - entity_id:
    - sensor.i_9psl_pm2_5
    above: 5
    id: turn-on
    trigger: numeric_state
  - entity_id:
    - sensor.i_9psl_pm10
    above: 15
    id: turn-on
    trigger: numeric_state
  - entity_id:
    - sensor.i_9psl_pm2_5
    - sensor.i_9psl_pm10
    id: turn-off
    below: 4
    for:
      hours: 0
      minutes: 5
      seconds: 0
    trigger: numeric_state
  conditions: []
  actions:
  - if:
    - condition: trigger
      id:
      - turn-on
    - condition: state
      entity_id: switch.plug_air_purifier_switch
      state: 'off'
    then:
    - metadata: {}
      data: {}
      target:
        entity_id:
        - switch.plug_air_purifier_switch
      action: switch.turn_on
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: switch.plug_air_purifier_switch
      state: 'on'
    then:
    - metadata: {}
      data: {}
      target:
        entity_id:
        - switch.plug_air_purifier_switch
      action: switch.turn_off
  mode: single
- id: '1719353854773'
  alias: automation-away-from-home
  description: ''
  triggers:
  - entity_id:
    - binary_sensor.sensor_inside_motion
    to: 'off'
    for:
      hours: 0
      minutes: 15
      seconds: 0
    trigger: state
  conditions:
  - condition: state
    entity_id: light.lights_all
    state: 'on'
  actions:
  - metadata: {}
    data: {}
    target:
      entity_id: light.lights_all
    action: light.turn_off
  mode: single
- id: '1722085260749'
  alias: automation-tv
  description: ''
  triggers:
  - entity_id:
    - media_player.philips_43pus8506_2
    attribute: app_id
    to: com.google.android.tvlauncher
    for:
      hours: 0
      minutes: 15
      seconds: 0
    trigger: state
  conditions: []
  actions:
  - metadata: {}
    data: {}
    target:
      entity_id: remote.philips_43pus8506
    action: remote.turn_off
  mode: single
- id: '1732381763504'
  alias: automation-remote
  description: ''
  triggers:
  - device_id: 7e0df21fba2ff631d282063e7bc97f81
    domain: zha
    type: remote_button_short_press
    subtype: turn_on
    trigger: device
    id: turn-on
  - device_id: 7e0df21fba2ff631d282063e7bc97f81
    domain: zha
    type: remote_button_short_press
    subtype: turn_off
    trigger: device
    id: turn-off
  conditions: []
  actions:
  - if:
    - condition: trigger
      id:
      - turn-on
    - condition: state
      entity_id: light.lights_bedroom
      state: 'off'
    then:
    - action: script.script_bedroom_lights_color
      metadata: {}
      data:
        transition: 1
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: light.lights_bedroom
      state: 'on'
    then:
    - action: light.turn_off
      metadata: {}
      data: {}
      target:
        entity_id:
        - light.lights_bedroom
  mode: single
- id: '1733714968098'
  alias: automation-phone
  description: ''
  triggers:
  - trigger: time
    at: 00:00:00
    id: low
  - trigger: time
    at: input_datetime.datetime_wakeup_time
    id: high
  conditions: []
  actions:
  - if:
    - condition: trigger
      id:
      - low
    then:
    - action: notify.notify
      metadata: {}
      data:
        message: command_screen_brightness_level
        data:
          command: 8
  - if:
    - condition: trigger
      id:
      - high
    then:
    - action: notify.notify
      metadata: {}
      data:
        message: command_screen_brightness_level
        data:
          command: 30
  mode: single
- id: '1739182251041'
  alias: automation-morning-sun-helper
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.sun_solar_rising
    to: 'False'
  conditions:
  - condition: state
    entity_id: input_boolean.boolean_wakeup_lights
    state: 'on'
  actions:
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
      - input_boolean.boolean_wakeup_lights
  mode: single
- id: '1739182323069'
  alias: automation-morning-wakeup-helper
  description: ''
  triggers:
  - entity_id:
    - sensor.pixel_8_next_alarm
    trigger: state
  - trigger: time
    at: 00:00:00
    enabled: false
  conditions: []
  actions:
  - if:
    - condition: template
      value_template: '{{ states(''sensor.pixel_8_next_alarm'') in ["unknown","unavailable"]
        }}'
    then:
    - metadata: {}
      data:
        timestamp: '{{ (as_timestamp(today_at(''09:30'')) | int ) }}'
      target:
        entity_id: input_datetime.time_wakeup_lights
      action: input_datetime.set_datetime
      enabled: false
    - metadata: {}
      data:
        timestamp: '{{ (as_timestamp(today_at(''09:30'')) | int ) }}'
      target:
        entity_id: input_datetime.datetime_wakeup_time
      action: input_datetime.set_datetime
    else:
    - metadata: {}
      data:
        timestamp: '{{ (as_timestamp(trigger.to_state.state) | int ) - 15*60 }}'
      target:
        entity_id: input_datetime.time_wakeup_lights
      action: input_datetime.set_datetime
      enabled: false
    - metadata: {}
      data:
        timestamp: '{{ (as_timestamp(trigger.to_state.state) | int ) - 15*60 }}'
      target:
        entity_id: input_datetime.datetime_wakeup_time
      action: input_datetime.set_datetime
  mode: single
- id: '1740349884876'
  alias: automation-bedroom-lights-morning
  description: ''
  triggers:
  - at: input_datetime.datetime_wakeup_time
    id: turn-on
    trigger: time
  - entity_id:
    - sensor.sensor_bedroom_entry_illuminance
    id: turn-off
    above: 60
    trigger: numeric_state
    enabled: false
  conditions:
  - condition: state
    entity_id: sensor.sun_solar_rising
    state: 'True'
  actions:
  - if:
    - condition: trigger
      id:
      - turn-on
    - condition: state
      entity_id: binary_sensor.sensor_bedroom_motion
      state: 'on'
      enabled: false
    - condition: state
      entity_id: input_boolean.boolean_wakeup_lights
      state: 'off'
    then:
    - metadata: {}
      data: {}
      target:
        entity_id:
        - input_boolean.boolean_wakeup_lights
      action: input_boolean.turn_on
    - action: script.script_bedroom_lights_full
      metadata: {}
      data:
        transition: 900
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: light.lights_bedroom
      state: 'on'
    then:
    - metadata: {}
      data:
        transition: 30
      target:
        entity_id:
        - light.lights_bedroom
      action: light.turn_off
  mode: single
- id: '1741003586439'
  alias: automation-lights-illum
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.sensor_outside_balcony_illuminance
    below: 3000
    id: turn-on
  - trigger: numeric_state
    entity_id:
    - sensor.sensor_outside_balcony_illuminance
    for:
      hours: 0
      minutes: 2
      seconds: 0
    above: 3000
    id: turn-off
  conditions:
  - condition: state
    entity_id: sensor.sun_solar_rising
    state: 'False'
  actions:
  - if:
    - condition: trigger
      id:
      - turn-on
    - condition: state
      entity_id: light.lights_livingroom
      state: 'off'
      enabled: true
    - condition: state
      entity_id: binary_sensor.sensor_livingroom_motion
      state: 'on'
    then:
    - action: script.script_livingroom_lights_full
      metadata: {}
      data:
        transition: 120
  - if:
    - condition: trigger
      id:
      - turn-on
    - condition: state
      entity_id: light.lights_bedroom
      state: 'off'
      enabled: true
    - condition: state
      entity_id: binary_sensor.sensor_bedroom_motion
      state: 'on'
    then:
    - action: script.script_bedroom_lights_full
      metadata: {}
      data:
        transition: 120
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: light.lights_livingroom
      state: 'on'
      enabled: true
    then:
    - action: light.turn_off
      metadata: {}
      data:
        transition: 30
      target:
        entity_id:
        - light.lights_livingroom
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: light.lights_bedroom
      state: 'on'
      enabled: true
    then:
    - action: light.turn_off
      metadata: {}
      data:
        transition: 30
      target:
        entity_id: light.lights_bedroom
  mode: single
- id: '1741004005554'
  alias: automation-lights-time
  description: ''
  triggers:
  - trigger: template
    value_template: '{% set hours = as_timestamp(states(''sensor.sun_next_dusk''))
      | timestamp_custom(''%H'') | int %}

      {% set min = as_timestamp(states(''sensor.sun_next_dusk'')) | timestamp_custom(''%M'')
      | int %}

      {% set ratio = 6/10 %}

      {{ as_timestamp(now()) | timestamp_custom(''%H:%M'') == (((24-hours-min/60)*ratio+hours+min/60)*60*60)
      | timestamp_custom(''%H:%M'', false) }}'
  conditions:
  - condition: state
    entity_id: light.lights_all
    state: 'on'
  actions:
  - action: script.script_livingroom_lights_color
    metadata: {}
    data:
      transition: 600
  - action: script.script_bedroom_lights_color
    metadata: {}
    data:
      transition: 600
  mode: single
- id: '1741029409508'
  alias: automation-lights-motion-bedroom
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.sensor_bedroom_entry_occupancy
    to: 'on'
    id: turn-on
    from: 'off'
  - trigger: state
    entity_id:
    - binary_sensor.sensor_bedroom_motion
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
    id: turn-off
    from: 'on'
  conditions: []
  actions:
  - if:
    - condition: trigger
      id:
      - turn-on
    - condition: state
      entity_id: light.lights_bedroom
      state: 'off'
      enabled: true
    - condition: numeric_state
      entity_id: sensor.sensor_outside_balcony_illuminance
      below: 3000
    then:
    - if:
      - condition: template
        value_template: '{% set hours = as_timestamp(states(''sensor.sun_next_dusk''))
          | timestamp_custom(''%H'') | int %}

          {% set min = as_timestamp(states(''sensor.sun_next_dusk'')) | timestamp_custom(''%M'')
          | int %}

          {% set ratio = 6/10 %}

          {{ as_timestamp(now()) | timestamp_custom(''%H:%M'') < (((24-hours-min/60)*ratio+hours+min/60)*60*60)
          | timestamp_custom(''%H:%M'', false) }}'
      - condition: time
        after: input_datetime.datetime_wakeup_time
      then:
      - action: script.script_bedroom_lights_full
        metadata: {}
        data:
          transition: 1
      else:
      - action: script.script_bedroom_lights_color
        metadata: {}
        data:
          transition: 1
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: light.lights_bedroom
      state: 'on'
      enabled: true
    then:
    - action: light.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: light.lights_bedroom
  mode: single
- id: '1741029438832'
  alias: automation-lights-motion-livingroom
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.sensor_livingroom_motion
    to: 'on'
    id: turn-on
    from: 'off'
  - trigger: state
    entity_id:
    - binary_sensor.sensor_livingroom_motion
    to: 'off'
    for:
      hours: 0
      minutes: 10
      seconds: 0
    id: turn-off
    from: 'on'
  conditions: []
  actions:
  - if:
    - condition: trigger
      id:
      - turn-on
    - condition: state
      entity_id: light.lights_livingroom
      state: 'off'
      enabled: true
    - condition: numeric_state
      entity_id: sensor.sensor_outside_balcony_illuminance
      below: 3000
    then:
    - if:
      - condition: template
        value_template: '{% set hours = as_timestamp(states(''sensor.sun_next_dusk''))
          | timestamp_custom(''%H'') | int %}

          {% set min = as_timestamp(states(''sensor.sun_next_dusk'')) | timestamp_custom(''%M'')
          | int %}

          {% set ratio = 6/10 %}

          {{ as_timestamp(now()) | timestamp_custom(''%H:%M'') < (((24-hours-min/60)*ratio+hours+min/60)*60*60)
          | timestamp_custom(''%H:%M'', false) }}'
      - condition: time
        after: input_datetime.datetime_wakeup_time
      then:
      - action: script.script_livingroom_lights_full
        metadata: {}
        data:
          transition: 1
      else:
      - action: script.script_livingroom_lights_color
        metadata: {}
        data:
          transition: 1
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: light.lights_livingroom
      state: 'on'
      enabled: true
    then:
    - action: light.turn_off
      metadata: {}
      data: {}
      target:
        entity_id:
        - light.lights_livingroom
  mode: single
