- id: '1708472646046'
  alias: automation-motion-kitchen
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.signify_netherlands_b_v_sml003_occupancy_2
    to: 'on'
    id: motion
  - platform: state
    entity_id:
    - binary_sensor.signify_netherlands_b_v_sml003_occupancy_2
    to: 'off'
    id: no-motion
    for:
      hours: 0
      minutes: 2
      seconds: 0
  - platform: state
    entity_id:
    - light.helper_light_kitchen
    to: 'on'
    for:
      hours: 0
      minutes: 20
      seconds: 0
    id: no-motion
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - motion
    - condition: state
      entity_id: light.helper_light_kitchen
      state: 'off'
    then:
    - service: light.turn_on
      target:
        entity_id:
        - light.helper_light_kitchen
      data: {}
  - if:
    - condition: trigger
      id:
      - no-motion
    - condition: state
      entity_id: light.helper_light_kitchen
      state: 'on'
    then:
    - service: light.turn_off
      target:
        entity_id:
        - light.helper_light_kitchen
      data:
        transition: 0.5
  mode: single
- id: '1708554610064'
  alias: automation-motion-bed
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.motion_bed_occupancy
    id: motion
    for:
      hours: 0
      minutes: 0
      seconds: 0
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.motion_bed_occupancy
    to: 'off'
    id: no-motion
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition:
  - condition: time
    before: '12:00:00'
  action:
  - if:
    - condition: trigger
      id:
      - motion
    - condition: state
      entity_id: light.helper_light_all
      state: 'off'
    then:
    - service: light.turn_on
      target:
        entity_id:
        - light.helper_light_dim
      data: {}
  - if:
    - condition: trigger
      id:
      - no-motion
    - condition: state
      entity_id: light.helper_light_dim
      state: 'on'
    then:
    - service: light.turn_off
      target:
        entity_id:
        - light.helper_light_dim
      data:
        transition: 0.5
  mode: single
- id: '1709248005558'
  alias: automation-sound-beamer
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.optoma_hd146x
    id: turn-on
    from: unavailable
    enabled: true
  - platform: state
    entity_id:
    - media_player.optoma_hd146x
    to: unavailable
    id: turn-off
    enabled: true
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - turn-on
    then:
    - if:
      - condition: state
        entity_id: media_player.denon_dra_800h
        state: 'off'
      then:
      - service: media_player.turn_on
        target:
          entity_id: media_player.denon_dra_800h
        data: {}
    - if:
      - condition: not
        conditions:
        - condition: state
          entity_id: media_player.denon_dra_800h
          attribute: source
          state: CBL/SAT
      then:
      - service: media_player.select_source
        target:
          entity_id: media_player.denon_dra_800h
        data:
          source: CBL/SAT
  - if:
    - condition: trigger
      id:
      - turn-off
    - condition: state
      entity_id: media_player.denon_dra_800h
      state: 'on'
    - condition: state
      entity_id: media_player.denon_dra_800h
      attribute: source
      state: CBL/SAT
    then:
    - service: media_player.turn_off
      target:
        entity_id:
        - media_player.denon_dra_800h
      data: {}
  mode: single
- id: '1715010154294'
  alias: automation-evening
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.signify_netherlands_b_v_sml004_illuminance
    for:
      hours: 0
      minutes: 5
      seconds: 0
    below: 450
    id: turn-on
  - platform: time
    at: 01:00:00
    enabled: true
    id: turn-off
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - turn-on
      enabled: true
    then:
    - service: light.turn_on
      data:
        kelvin: 2600
        transition: 900
        brightness_pct: 75
      target:
        entity_id:
        - light.helper_light_full
    - service: light.turn_on
      target:
        entity_id:
        - light.helper_light_dim
      data:
        kelvin: 2600
        brightness_pct: 50
        transition: 900
    - service: notify.notify
      metadata: {}
      data:
        message: LIGHTS ON
  - if:
    - condition: trigger
      id:
      - turn-off
    then:
    - service: light.turn_off
      data:
        transition: 0.5
      target:
        entity_id:
        - light.helper_light_full
        - light.helper_light_dim
    enabled: true
  mode: single
- id: '1715010176073'
  alias: automation-morning
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.kb2003_next_alarm
    id: set-time
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - platform: numeric_state
    entity_id:
    - sensor.signify_netherlands_b_v_sml004_illuminance
    for:
      hours: 0
      minutes: 5
      seconds: 0
    above: 450
    id: turn-on-sun
  - platform: time
    at: input_datetime.helper_time_offset
    id: turn-on-alarm
    enabled: true
  - platform: time
    at: '12:00:00'
    id: turn-off
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - set-time
    then:
    - if:
      - condition: template
        value_template: '{{ trigger.to_state.state in ["unknown","unavailable"] }}'
      then:
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.helper_time_offset
        data:
          datetime: '1970-01-01 00:00:00'
      else:
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.helper_time_offset
        data:
          timestamp: '{{ (as_timestamp(trigger.to_state.state) | int ) - 15*60 }}'
        enabled: true
      enabled: true
    enabled: true
  - if:
    - condition: trigger
      id:
      - turn-on-alarm
      - turn-on-sun
      enabled: true
    - condition: template
      value_template: '{% set x = states(''sensor.kb2003_next_alarm'') in ["unknown","unavailable"]
        %}

        {% set y = now().hour >= 12 %}

        {{ x or y if trigger.id in [''turn-on-sun''] else True }}

        '
      enabled: true
    - condition: template
      value_template: '{% set x = now().hour < 12 %}

        {{ x if trigger.id in [''turn-on-alarm''] else True }}

        '
      enabled: true
    then:
    - service: light.turn_on
      target:
        entity_id:
        - light.helper_light_full
      data:
        kelvin: 3800
        brightness_pct: 100
        transition: 900
      enabled: true
    - service: light.turn_on
      target:
        entity_id:
        - light.helper_light_dim
      data:
        kelvin: 3800
        brightness_pct: 75
        transition: 900
      enabled: true
    enabled: true
  - if:
    - condition: trigger
      id:
      - turn-off
      enabled: true
    then:
    - service: light.turn_off
      target:
        entity_id:
        - light.helper_light_dim
      data:
        transition: 0.5
    enabled: true
  mode: single
- id: '1715803115351'
  alias: automation-remote
  description: ''
  trigger:
  - device_id: 89d6bbe7751aeb89cd3830d0c6644683
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
    id: press-on
  - device_id: 89d6bbe7751aeb89cd3830d0c6644683
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: dim_up
    id: press-up
  - device_id: 89d6bbe7751aeb89cd3830d0c6644683
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: dim_down
    id: press-down
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - press-on
    then:
    - service: light.toggle
      target:
        entity_id: light.helper_light_all
      data:
        transition: 0.5
  - if:
    - condition: trigger
      id:
      - press-up
    then:
    - service: light.toggle
      data:
        transition: 0.5
      target:
        entity_id:
        - light.helper_light_tv
  - if:
    - condition: trigger
      id:
      - press-down
    then:
    - service: light.toggle
      target:
        entity_id:
        - light.helper_light_dim
      data:
        transition: 0.5
  mode: single
