- id: '1706919178130'
  alias: automation-evening
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.sun_solar_elevation
    below: 10
    id: turn-lights-on
    enabled: true
  - platform: time
    at: 01:00:00
    enabled: true
    id: turn-lights-off
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - turn-lights-on
    then:
    - service: automation.trigger
      metadata: {}
      data:
        skip_condition: true
      target:
        entity_id: automation.automation_turn_on_lights
  - if:
    - condition: trigger
      id:
      - turn-lights-off
    then:
    - service: automation.trigger
      metadata: {}
      data:
        skip_condition: true
      target:
        entity_id: automation.automation_turn_off_lights
    enabled: true
  mode: single
- id: '1707239925785'
  alias: automation-turn_on_lights
  description: ''
  trigger: []
  condition: []
  action:
  - if:
    - condition: state
      entity_id: light.helper_all_entities
      state: 'off'
      enabled: true
    then:
    - service: notify.notify
      metadata: {}
      data:
        message: LIGHTS ON
    - service: light.turn_on
      target:
        entity_id: light.helper_all
      data:
        brightness_pct: 1
        kelvin: '{{ 4000 if now().hour < 12 else 2800 }}'
    - service: light.turn_on
      data:
        transition: 600
        brightness_pct: 65
      target:
        entity_id: light.helper_dim
    - service: light.turn_on
      data:
        transition: 600
        brightness_pct: 100
      target:
        entity_id: light.helper_full
  mode: single
- id: '1707239957242'
  alias: automation-turn_off_lights
  description: ''
  trigger: []
  condition: []
  action:
  - if:
    - condition: state
      entity_id: light.helper_all
      state: 'on'
    then:
    - service: notify.notify
      metadata: {}
      data:
        message: LIGHTS OFF
    - service: light.turn_off
      target:
        entity_id:
        - light.helper_all
      data: {}
  mode: single
- id: '1707333453641'
  alias: automation-morning
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.kb2003_next_alarm
    id: set-time
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - platform: time
    at: input_datetime.helper_time_offset
    id: action-on-alarm
    enabled: true
  - platform: numeric_state
    entity_id:
    - sensor.sun_solar_elevation
    above: 9
    id: action-on-sun
    enabled: true
  - platform: time
    at: '12:00:00'
    id: action-off
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - set-time
    then:
    - if:
      - condition: template
        value_template: '{{ trigger.to_state.state in ["unknown","unavailable"] }}'
      then:
      - service: notify.notify
        metadata: {}
        data:
          message: SET ALARM (00:00)
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.helper_time_offset
        data:
          datetime: '1970-01-01 00:00:00'
      else:
      - service: notify.notify
        metadata: {}
        data:
          message: SET ALARM (time)
      - variables:
          offset_alarm: 15
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.helper_time_offset
        data:
          timestamp: '{{ (as_timestamp(trigger.to_state.state) | int ) - offset_alarm*60
            }}'
        enabled: true
      enabled: true
    enabled: true
  - if:
    - condition: trigger
      id:
      - action-on-alarm
      - action-on-sun
    - condition: template
      value_template: '{% set x = as_timestamp(now())|timestamp_custom("%H:%M") <
        states(''input_datetime.helper_time_max_alarm'') %}

        {{ x if trigger.id in [''action-on-alarm''] else True }}

        '
      enabled: true
    - condition: template
      value_template: '{% set x = states(''sensor.kb2003_next_alarm'') in ["unknown","unavailable"]
        %}

        {% set y = as_timestamp(now())|timestamp_custom("%H:%M") > states(''input_datetime.helper_time_max_alarm'')
        %}

        {{ x or y if trigger.id in [''action-on-sun''] else True }}

        '
      enabled: true
    then:
    - service: automation.trigger
      metadata: {}
      data:
        skip_condition: true
      target:
        entity_id: automation.automation_turn_on_lights
    enabled: true
  - if:
    - condition: trigger
      id:
      - action-off
    then:
    - service: automation.trigger
      metadata: {}
      data:
        skip_condition: true
      target:
        entity_id: automation.automation_turn_off_lights
    enabled: true
  mode: single
- id: '1707568193168'
  alias: automation-test
  description: ''
  trigger: []
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.helper_all
    data:
      brightness: 0
    enabled: true
  - service: light.turn_on
    target:
      entity_id: light.helper_all
    data:
      transition: 30
      kelvin: 6500
      brightness_pct: 100
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
    enabled: false
  - service: light.turn_on
    target:
      entity_id: light.helper_all
    data:
      transition: 30
      brightness_step_pct: 100
      brightness_pct: 100
    enabled: false
  mode: single
