---
version: '3'

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    hostname: homeassistant
    network_mode: host
    restart: unless-stopped
    privileged: true
    environment:
      TZ: "${DEVICE_TIMEZONE}"
    volumes:
      - volume_homeassistant:/config
      - /run/dbus:/run/dbus:ro
#    devices:
#      - /dev/ttyUSB0:/dev/ttyUSB0

volumes:
  volume_homeassistant:
    external: true
