blueprint:
  name: test blueprint
  description: ''
  domain: automation

  input:
    entity-all-lights-entities:
      name: Entity selector
      description: "Select the group with all the lights (w/ 'all entities')"
      selector:
        entity:
          filter:
            domain: light
    entity-all-lights:
      name: Entity selector
      description: "Select the group with all the lights (w/o 'all entities')"
      selector:
        entity:
          filter:
            domain: light
    entity-dim-lights:
      name: Entity selector
      description: "Select the group with the lights being dimmed"
      selector:
        entity:
          filter:
            domain: light
    entity-full-lights:
      name: Entity selector
      description: "Select the group with the lights on full brightness"
      selector:
        entity:
          filter:
            domain: light

    color_temp:
      name: Color temperature
      description: "Select the color temperature you want the lights to turn on in the evening"
      selector:
        color_temp:
          unit: kelvin
          min: 2000
          max: 6500
    duration:
      name: Duration selector
      description: "Select the time offset you want the lights to turn on before/after the sunset"
      selector:
        duration:
    number:
      name: Number selector
      description: "Select the brightness for the lights"
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider
    time:
      name: Time selector
      description: "Select "
      selector:
        time:
