blueprint:
  name: test blueprint
  description: ''
  domain: automation

  input:
    color_temp:
      name: Color temperature
      description: "Select the color temperature you want the lights to turn on in the evening"
      selector:
        color_temp:
          unit: kelvin
          min: 2000
          max: 6500
    duration:
      name: Duration selector
      description: "Select the time offset you want the lights to turn on before/after the sunset"
      selector:
        duration:
    entity:
      name: Entity selector
      description: "Select "
      selector:
        entity:
          filter:
            domain: light
    number:
      name: Number selector
      description: "Select the brightness for the lights"
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider
    time:
      name: Time selector
      description: "Select "
      selector:
        time:
