---
- name: 'DOCKER : copy docker env file'
  ansible.builtin.template:
    src: templates/.env.j2
    dest: files/.env
    mode: '0644'

- name: 'DOCKER : create volume'
  community.docker.docker_volume:
    name: volume_homeassistant
  become: true

- name: 'DOCKER : copy config in volume'
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - { src: files/automations.yaml, dest: /var/lib/docker/volumes/volume_homeassistant/_data/ }
    - { src: files/scenes.yaml, dest: /var/lib/docker/volumes/volume_homeassistant/_data/ }
    - { src: files/lovelace, dest: /var/lib/docker/volumes/volume_homeassistant/_data/.storage/ }
  become: true

- name: 'DOCKER : create containers'
  community.docker.docker_compose_v2:
    project_src: files/
    pull: always
#    recreate: always
  become: true

- name: 'DOCKER : remove unused images'
  community.docker.docker_prune:
    images: true
  become: true
